resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/wocgc-app     
    newName: 560971842042.dkr.ecr.ap-northeast-2.amazonaws.com/wocgc-app
    newTag: latest
